default: 
	gcc -g -Wall -Wextra -o server server.c
	gcc -g -Wall -Wextra -o client client.c
dist: 
	tar -czvf project2_804769644_404729909.tar.gz server.c Makefile README
clean: 
	rm -f server project2_804769644_404729909.tar.gz